"""LLM task augmentation (paper: 100 variants generated by Claude Opus, then human-validated).

Each variant changes objectives, spawn locations and initial items while preserving the need to
collaborate. On top of the paper's procedure, every variant must ship a reference solution that
the scripted agent replays in the simulator: a variant is kept only if it validates statically,
is not already solved at round 0, and its reference solution actually succeeds within budget.
Kept variants are still marked needs_human_review.
"""

from __future__ import annotations

from pathlib import Path

import yaml

from . import content as C
from .gamemap import WORLD_GUIDE
from .llm import ClaudeClient
from .runner import make_factory, run_episode
from .task import Task
from .verifier import CHECKPOINT_TYPES, evaluate

SYSTEM = "You design tasks for a multi-agent RPG benchmark. You write precise, valid YAML and check feasibility carefully."

PROMPT = """Create variant #{k} of the benchmark task below.

Change the objective (different target items/quantities/locations), the spawn locations and the initial
items, but keep the same category ({category}) and keep collaboration NECESSARY: no single agent may be
able to finish alone (use skill levels, tools, restricted_tools and private role briefs to enforce it).
Use only content that exists in the game (listed below). Keep max_rounds between 20 and 55.
Include a `reference_solution`: for every agent a list of [tool, {{args}}] steps (optionally a third
element {{retries: n}} so a step that fails while waiting for teammates is retried). The reference
solution will be executed in the simulator; the variant is rejected if it does not succeed.
Previously generated variants of this task (make yours meaningfully different): {previous}

=== SOURCE TASK (YAML) ===
{source}

=== GAME CONTENT ===
{content}

Checkpoint types for the verifier: {cp_types}
Checkpoint fields: has_item(agent|any, item, count), team_total(item, count), equipped(agent, item),
kills(mob, count, agent?), all_alive, in_region(agents, rect[x0,y0,x1,y1]), near(agents, pos, radius),
structure(structure, count, near?, radius?), plates, entity_defeated(entity), rounds_survived(rounds).
Rules: agents spawn on walkable tiles (not lake x22-44/y35-46, not the dungeon wall x=45 or y=20 for x>=45);
harvest/attack/buy/sell/transfer auto-walk up to 12 steps; move_to moves up to 12 tiles; smithing needs the
anvil (33,19); cooking needs the stove (36,19) or a campfire; building is not allowed inside the village.

Return JSON with: task_yaml (the complete YAML of the new task, new unique id `{new_id}`),
changes (list of what you changed), collaboration_rationale (why one agent cannot do it alone)."""

FIX_PROMPT = """Your variant was rejected:
{problem}
Fix the task (and/or its reference_solution) and return the complete corrected JSON again."""

SCHEMA = {
    "type": "object",
    "properties": {
        "task_yaml": {"type": "string"},
        "changes": {"type": "array", "items": {"type": "string"}},
        "collaboration_rationale": {"type": "string"},
    },
    "required": ["task_yaml", "changes", "collaboration_rationale"],
    "additionalProperties": False,
}


def content_summary() -> str:
    lines = [WORLD_GUIDE, "Skills: " + ", ".join(C.SKILLS)]
    lines.append("Recipes:\n" + "\n".join("  " + C.describe_recipe(k) for k in C.RECIPES))
    lines.append("Structures:\n" + "\n".join("  " + C.describe_structure(k) for k in C.STRUCTURES))
    lines.append("Resources (type: item, skill lvl, tool):\n" + "\n".join(
        f"  {k}: {v['item']}, {v['skill']} {v['level']}, {v['tool']}" for k, v in C.RESOURCES.items()))
    lines.append("Mobs (type: lvl, hp, atk, def, drops, aggro radius):\n" + "\n".join(
        f"  {k}: {v['level']}, {v['hp']}, {v['attack']}, {v['defense']}, {v['drops']}, {v['aggro_radius']}" for k, v in C.MOBS.items()))
    lines.append("Shops:\n" + "\n".join(f"  {k}: sells {v['sells']} buys {v['buys']}" for k, v in C.SHOPS.items()))
    lines.append("Items: " + ", ".join(f"{k}({v['kind']})" for k, v in C.ITEMS.items()))
    lines.append("Extra entity kinds: mob (type, id, pos, hp?, regen?, attack?, aggro_radius?), landmark (ancient_shrine, reveal?),"
                 " plate (color), resource, npc, station.")
    return "\n".join(lines)


def check_variant(task: Task) -> str | None:
    errors, warnings = task.validate()
    if errors:
        return "Static validation errors: " + "; ".join(errors)
    collab = [w for w in warnings if "alone" in w]
    if collab:
        return "Collaboration not required: " + "; ".join(collab)
    if evaluate(task.build_world(), task.verifier)["success"]:
        return "The objective is already satisfied at round 0."
    if not task.reference_solution:
        return "Missing reference_solution."
    traj = run_episode(task, make_factory("scripted"))
    if not traj["result"]["success"]:
        tail = "\n".join(a["description"][:200] for a in traj["actions"][-12:])
        return (f"Reference solution failed ({traj['result']['message']}) after {traj['result']['rounds_used']} rounds. "
                f"Last actions:\n{tail}")
    return None


def augment_task(src: Task, client: ClaudeClient, k: int, previous: list[str], max_fix: int = 2) -> tuple[Task | None, dict]:
    source = dict(src.to_dict())
    source.pop("reference_solution", None)
    new_id = f"{src.id}_v{k}"
    prompt = PROMPT.format(
        k=k, category=src.category, previous=previous or "none", new_id=new_id,
        source=yaml.safe_dump(source, sort_keys=False, allow_unicode=True),
        content=content_summary(), cp_types=", ".join(CHECKPOINT_TYPES))
    log: dict = {"source": src.id, "attempts": []}
    messages_prompt = prompt
    for attempt in range(max_fix + 1):
        data, usage = client.json_call(SYSTEM, messages_prompt, SCHEMA, max_tokens=16000)
        problem = None
        task = None
        try:
            d = yaml.safe_load(data["task_yaml"])
            d["id"] = new_id
            d["category"] = src.category
            task = Task.from_dict(d)
            problem = check_variant(task)
        except Exception as exc:  # malformed YAML / schema
            problem = f"Could not parse the task: {exc!r}"
        log["attempts"].append({"problem": problem, "usage": usage})
        if problem is None:
            task.meta.update({
                "augmented_from": src.id, "needs_human_review": True,
                "changes": data["changes"], "collaboration_rationale": data["collaboration_rationale"],
            })
            return task, log
        messages_prompt = prompt + "\n\nPrevious attempt:\n" + data["task_yaml"] + "\n\n" + FIX_PROMPT.format(problem=problem)
    return None, log


def save_task(task: Task, out_dir: str | Path) -> Path:
    out = Path(out_dir)
    out.mkdir(parents=True, exist_ok=True)
    p = out / f"{task.id}.yaml"
    p.write_text(yaml.safe_dump(task.to_dict(), sort_keys=False, allow_unicode=True), encoding="utf-8")
    return p
